apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-userdata
  labels:
    app: wordpress
spec:
  ports:
    - port: 3307
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-userdata
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql-userdata
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mysql-userdata
        image: nzgeg3s0/mysql-honeypot
        # command: [""]
        # args: ["-s", "5.6", "-f"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-user
              key: password
        - name: NTFY_USER
          valueFrom:
            secretKeyRef:
              name: ntfy-creds
              key: user
        - name: NTFY_PASS
          valueFrom:
            secretKeyRef:
              name: ntfy-creds
              key: pass
        ports:
        - containerPort: 3307
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-userdata
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-userdata
        persistentVolumeClaim:
          claimName: mysql-pv-claim-userdata
