apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-replica
spec:
  selector:
    matchLabels:
      app: mysql-replica
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-replica
    spec:
      containers:
      - name: mysql-replica
        image: nzgeg3s0/mysql-honeypot
        ports:
        - containerPort: 3307
